apiVersion: v1
kind: Service
metadata:
  name: gitdata-ai-blog-service
  labels:
    apptype: gitdata-ai-blog
spec:
  type: ClusterIP
  selector:
    app: gitdata-ai-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80